<?php

use App\Database;

// $statement = $pdo->exec('INSERT INTO post SET title="Mon titre", content="contenu sutitre",
//                       image="https://lorempixel.com/640/480/?51191",category_id=56,
//                        created_at="' . date('y/m/d H:i:s') . '"');
// $res = $pdo->query('SELECT * FROM post');
// //$res = $statement->fetchAll();
// $datas = $res->fetchAll(PDO::FETCH_OBJ);
// //dump($res);
// dump($datas[0]);

//<?php var_dump($post) 
?>

<div class="container mt-5">
    <div class="row">
        <?php foreach ($db->query('SELECT * FROM post', 'App\Table\Post') as $post) : ?>
            <div class="col-md-4">
                <div class="card p-2">
                    <h2 class="card-title">

                        <a href="<?= $post->url ?>"><?= $post->title ?></a>
                    </h2>
                    <div class="card-body">
                        <p class="card-text"><?= $post->extrait ?></p>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>