<?php

use App\App;
use App\Table\Category;
use App\Table\Post;

$post = Post::find($_GET['id']);
$categorie = Category::find($post->category_id);
if ($post == false) {
    App::notFound();
}


?>
<div class='container mt-5'>

    <div class="col-md-12">
        <div class="card p-2">
            <h2 class="card-title text-center">

                <a href="<?= $post->url ?>"><?= $post->title ?></a>

            </h2>
            <p class="text-center">Categorie: <em><a href="<?= $categorie->url ?>"><?= $categorie->title ?></a></em></p>
            <div class="card-body">
                <p class="card-text"><?= $post->content ?></p>
            </div>
        </div>
    </div>
</div>