<?php

use App\Table\Category;
use App\Table\Post;
use App\App;

$categorie = Category::find($_GET['id']);
if ($categorie == false) {
    App::notFound();
}
$posts = Post::lastByCategory($_GET['id']);
$categories = Category::findAll();
?>


<div class="container mt-5">
    <h1 class="text-lead"><?= $categorie->title ?></h1>
    <div class="row">
        <div class="col-md-8">
            <div class="row">
                <?php foreach ($posts as $post) : ?>
                    <div class="col-md-4">
                        <div class="card p-2">
                            <h2 class="card-title">

                                <a href="<?= $post->url ?>"><?= $post->title ?></a>
                            </h2>
                            <p class="lead">Categorie: <em><?= $post->category ?></em></p>
                            <div class="card-body">
                                <p class="card-text"><?= $post->extrait ?></p>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="col-md-4">
            <h2 class="text-dark">Les Categories</h2>
            <ul>
                <?php foreach ($categories as $categorie) : ?>
                    <li><a href="<?= $categorie->url ?>"><?= $categorie->title ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>