<?php

$app=App::getInstance();
$post =$app->getTable('Post')->findByCategoryId($_GET['id']);

if ($post == false) {
    $app->notFound();
}


?>
<div class='container mt-5'>

    <div class="col-md-12">
        <div class="card p-2">
            <h2 class="card-title text-center">

                <a href="<?= $post->url ?>"><?= $post->title ?></a>

            </h2>
            <p class="text-center">Categorie: <em><?= $post->category_id ?></a></em></p>
            <div class="card-body">
                <p class="card-text"><?= $post->content ?></p>
            </div>
        </div>
    </div>
</div>